// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package store

import (
	"context"
	"database/sql"
)

const attachTagToCalendar = `-- name: AttachTagToCalendar :exec
INSERT OR IGNORE INTO calendar_tags (event_id, tag_id) VALUES (?, ?)
`

type AttachTagToCalendarParams struct {
	EventID int64 `json:"event_id"`
	TagID   int64 `json:"tag_id"`
}

func (q *Queries) AttachTagToCalendar(ctx context.Context, arg AttachTagToCalendarParams) error {
	_, err := q.db.ExecContext(ctx, attachTagToCalendar, arg.EventID, arg.TagID)
	return err
}

const countCalendarEvents = `-- name: CountCalendarEvents :one
SELECT COUNT(*) FROM calendar_events WHERE deleted_at IS NULL
`

func (q *Queries) CountCalendarEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCalendarEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCalendarEvent = `-- name: CreateCalendarEvent :one
INSERT INTO calendar_events (
    title, description, start_at, end_at, all_day, location, category_id, notes, recurrence
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, description, start_at, end_at, all_day, location, category_id, notes, recurrence, created_at, updated_at, deleted_at
`

type CreateCalendarEventParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	StartAt     string         `json:"start_at"`
	EndAt       sql.NullString `json:"end_at"`
	AllDay      int64          `json:"all_day"`
	Location    string         `json:"location"`
	CategoryID  sql.NullInt64  `json:"category_id"`
	Notes       sql.NullString `json:"notes"`
	Recurrence  string         `json:"recurrence"`
}

func (q *Queries) CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, createCalendarEvent,
		arg.Title,
		arg.Description,
		arg.StartAt,
		arg.EndAt,
		arg.AllDay,
		arg.Location,
		arg.CategoryID,
		arg.Notes,
		arg.Recurrence,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
		&i.AllDay,
		&i.Location,
		&i.CategoryID,
		&i.Notes,
		&i.Recurrence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const detachAllTagsFromCalendar = `-- name: DetachAllTagsFromCalendar :exec
DELETE FROM calendar_tags WHERE event_id = ?
`

func (q *Queries) DetachAllTagsFromCalendar(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, detachAllTagsFromCalendar, eventID)
	return err
}

const getCalendarEvent = `-- name: GetCalendarEvent :one
SELECT id, title, description, start_at, end_at, all_day, location, category_id, notes, recurrence, created_at, updated_at, deleted_at FROM calendar_events WHERE id = ? LIMIT 1
`

func (q *Queries) GetCalendarEvent(ctx context.Context, id int64) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, getCalendarEvent, id)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
		&i.AllDay,
		&i.Location,
		&i.CategoryID,
		&i.Notes,
		&i.Recurrence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCalendarEvents = `-- name: ListCalendarEvents :many
SELECT id, title, description, start_at, end_at, all_day, location, category_id, notes, recurrence, created_at, updated_at, deleted_at FROM calendar_events
WHERE deleted_at IS NULL
ORDER BY start_at ASC, created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListCalendarEventsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCalendarEvents(ctx context.Context, arg ListCalendarEventsParams) ([]CalendarEvent, error) {
	rows, err := q.db.QueryContext(ctx, listCalendarEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsToday = `-- name: ListEventsToday :many
SELECT id, title, description, start_at, end_at, all_day, location, category_id, notes, recurrence, created_at, updated_at, deleted_at FROM calendar_events
WHERE deleted_at IS NULL
  AND start_at >= ? AND start_at <= ?
ORDER BY start_at ASC, id ASC
`

type ListEventsTodayParams struct {
	StartAt   string `json:"start_at"`
	StartAt_2 string `json:"start_at_2"`
}

// Events whose start_at falls within [dayStart, dayEnd]. The provider passes
// bounds formatted for the all_day branch (date) or timed branch (datetime).
func (q *Queries) ListEventsToday(ctx context.Context, arg ListEventsTodayParams) ([]CalendarEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEventsToday, arg.StartAt, arg.StartAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsUpcoming = `-- name: ListEventsUpcoming :many
SELECT id, title, description, start_at, end_at, all_day, location, category_id, notes, recurrence, created_at, updated_at, deleted_at FROM calendar_events
WHERE deleted_at IS NULL
  AND start_at > ? AND start_at <= ?
ORDER BY start_at ASC, id ASC
`

type ListEventsUpcomingParams struct {
	StartAt   string `json:"start_at"`
	StartAt_2 string `json:"start_at_2"`
}

// Events whose start_at falls within (dayEnd, weekEnd].
func (q *Queries) ListEventsUpcoming(ctx context.Context, arg ListEventsUpcomingParams) ([]CalendarEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEventsUpcoming, arg.StartAt, arg.StartAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForCalendar = `-- name: ListTagsForCalendar :many
SELECT t.id, t.name
FROM tags t
JOIN calendar_tags ct ON ct.tag_id = t.id
WHERE ct.event_id = ?
ORDER BY t.name ASC
`

func (q *Queries) ListTagsForCalendar(ctx context.Context, eventID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForCalendar, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedCalendarEvents = `-- name: ListTrashedCalendarEvents :many
SELECT id, title, description, start_at, end_at, all_day, location, category_id, notes, recurrence, created_at, updated_at, deleted_at FROM calendar_events
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id DESC
`

func (q *Queries) ListTrashedCalendarEvents(ctx context.Context) ([]CalendarEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTrashedCalendarEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeCalendarEvent = `-- name: PurgeCalendarEvent :exec
DELETE FROM calendar_events WHERE id = ?
`

func (q *Queries) PurgeCalendarEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, purgeCalendarEvent, id)
	return err
}

const restoreCalendarEvent = `-- name: RestoreCalendarEvent :exec
UPDATE calendar_events
SET deleted_at = NULL
WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreCalendarEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreCalendarEvent, id)
	return err
}

const softDeleteCalendarEvent = `-- name: SoftDeleteCalendarEvent :exec
UPDATE calendar_events
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCalendarEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteCalendarEvent, id)
	return err
}

const updateCalendarEvent = `-- name: UpdateCalendarEvent :one
UPDATE calendar_events
SET title = ?, description = ?, start_at = ?, end_at = ?, all_day = ?,
    location = ?, category_id = ?, notes = ?, recurrence = ?
WHERE id = ?
RETURNING id, title, description, start_at, end_at, all_day, location, category_id, notes, recurrence, created_at, updated_at, deleted_at
`

type UpdateCalendarEventParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	StartAt     string         `json:"start_at"`
	EndAt       sql.NullString `json:"end_at"`
	AllDay      int64          `json:"all_day"`
	Location    string         `json:"location"`
	CategoryID  sql.NullInt64  `json:"category_id"`
	Notes       sql.NullString `json:"notes"`
	Recurrence  string         `json:"recurrence"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateCalendarEvent(ctx context.Context, arg UpdateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, updateCalendarEvent,
		arg.Title,
		arg.Description,
		arg.StartAt,
		arg.EndAt,
		arg.AllDay,
		arg.Location,
		arg.CategoryID,
		arg.Notes,
		arg.Recurrence,
		arg.ID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
		&i.AllDay,
		&i.Location,
		&i.CategoryID,
		&i.Notes,
		&i.Recurrence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
