// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance.sql

package store

import (
	"context"
	"database/sql"
)

const attachTagToFinance = `-- name: AttachTagToFinance :exec
INSERT OR IGNORE INTO finance_tags (finance_id, tag_id) VALUES (?, ?)
`

type AttachTagToFinanceParams struct {
	FinanceID int64 `json:"finance_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) AttachTagToFinance(ctx context.Context, arg AttachTagToFinanceParams) error {
	_, err := q.db.ExecContext(ctx, attachTagToFinance, arg.FinanceID, arg.TagID)
	return err
}

const countFinanceTransactions = `-- name: CountFinanceTransactions :one
SELECT COUNT(*) FROM finance_transactions WHERE deleted_at IS NULL
`

func (q *Queries) CountFinanceTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFinanceTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFinanceTransaction = `-- name: CreateFinanceTransaction :one
INSERT INTO finance_transactions (
    date, amount, kind, account, category_id, notes, recurrence, currency
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, date, amount, kind, account, category_id, notes, recurrence, currency, created_at, updated_at, deleted_at
`

type CreateFinanceTransactionParams struct {
	Date       string         `json:"date"`
	Amount     float64        `json:"amount"`
	Kind       string         `json:"kind"`
	Account    string         `json:"account"`
	CategoryID sql.NullInt64  `json:"category_id"`
	Notes      sql.NullString `json:"notes"`
	Recurrence string         `json:"recurrence"`
	Currency   string         `json:"currency"`
}

func (q *Queries) CreateFinanceTransaction(ctx context.Context, arg CreateFinanceTransactionParams) (FinanceTransaction, error) {
	row := q.db.QueryRowContext(ctx, createFinanceTransaction,
		arg.Date,
		arg.Amount,
		arg.Kind,
		arg.Account,
		arg.CategoryID,
		arg.Notes,
		arg.Recurrence,
		arg.Currency,
	)
	var i FinanceTransaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Amount,
		&i.Kind,
		&i.Account,
		&i.CategoryID,
		&i.Notes,
		&i.Recurrence,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const detachAllTagsFromFinance = `-- name: DetachAllTagsFromFinance :exec
DELETE FROM finance_tags WHERE finance_id = ?
`

func (q *Queries) DetachAllTagsFromFinance(ctx context.Context, financeID int64) error {
	_, err := q.db.ExecContext(ctx, detachAllTagsFromFinance, financeID)
	return err
}

const getFinanceTransaction = `-- name: GetFinanceTransaction :one
SELECT id, date, amount, kind, account, category_id, notes, recurrence, currency, created_at, updated_at, deleted_at FROM finance_transactions WHERE id = ? LIMIT 1
`

func (q *Queries) GetFinanceTransaction(ctx context.Context, id int64) (FinanceTransaction, error) {
	row := q.db.QueryRowContext(ctx, getFinanceTransaction, id)
	var i FinanceTransaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Amount,
		&i.Kind,
		&i.Account,
		&i.CategoryID,
		&i.Notes,
		&i.Recurrence,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFinanceByMonth = `-- name: ListFinanceByMonth :many
SELECT id, date, amount, kind, account, category_id, notes, recurrence, currency, created_at, updated_at, deleted_at FROM finance_transactions
WHERE kind = 'expense'
  AND deleted_at IS NULL
  AND date >= ? AND date <= ?
ORDER BY date DESC, created_at DESC
`

type ListFinanceByMonthParams struct {
	Date   string `json:"date"`
	Date_2 string `json:"date_2"`
}

func (q *Queries) ListFinanceByMonth(ctx context.Context, arg ListFinanceByMonthParams) ([]FinanceTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listFinanceByMonth, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceTransaction{}
	for rows.Next() {
		var i FinanceTransaction
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Amount,
			&i.Kind,
			&i.Account,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinanceTransactions = `-- name: ListFinanceTransactions :many
SELECT id, date, amount, kind, account, category_id, notes, recurrence, currency, created_at, updated_at, deleted_at FROM finance_transactions
WHERE deleted_at IS NULL
ORDER BY date DESC, created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListFinanceTransactionsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListFinanceTransactions(ctx context.Context, arg ListFinanceTransactionsParams) ([]FinanceTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listFinanceTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceTransaction{}
	for rows.Next() {
		var i FinanceTransaction
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Amount,
			&i.Kind,
			&i.Account,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForFinance = `-- name: ListTagsForFinance :many
SELECT t.id, t.name
FROM tags t
JOIN finance_tags ft ON ft.tag_id = t.id
WHERE ft.finance_id = ?
ORDER BY t.name ASC
`

func (q *Queries) ListTagsForFinance(ctx context.Context, financeID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForFinance, financeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedFinanceTransactions = `-- name: ListTrashedFinanceTransactions :many
SELECT id, date, amount, kind, account, category_id, notes, recurrence, currency, created_at, updated_at, deleted_at FROM finance_transactions
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id DESC
`

func (q *Queries) ListTrashedFinanceTransactions(ctx context.Context) ([]FinanceTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listTrashedFinanceTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceTransaction{}
	for rows.Next() {
		var i FinanceTransaction
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Amount,
			&i.Kind,
			&i.Account,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeFinanceTransaction = `-- name: PurgeFinanceTransaction :exec
DELETE FROM finance_transactions WHERE id = ?
`

func (q *Queries) PurgeFinanceTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, purgeFinanceTransaction, id)
	return err
}

const restoreFinanceTransaction = `-- name: RestoreFinanceTransaction :exec
UPDATE finance_transactions
SET deleted_at = NULL
WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreFinanceTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreFinanceTransaction, id)
	return err
}

const softDeleteFinanceTransaction = `-- name: SoftDeleteFinanceTransaction :exec
UPDATE finance_transactions
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteFinanceTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteFinanceTransaction, id)
	return err
}

const topCategoriesByMonth = `-- name: TopCategoriesByMonth :many
SELECT
    c.name AS category_name,
    COALESCE(SUM(f.amount), 0) AS total
FROM finance_transactions f
LEFT JOIN categories c ON c.id = f.category_id
WHERE f.kind = 'expense'
  AND f.deleted_at IS NULL
  AND f.date >= ? AND f.date <= ?
GROUP BY c.id
ORDER BY total DESC
LIMIT ?
`

type TopCategoriesByMonthParams struct {
	Date   string `json:"date"`
	Date_2 string `json:"date_2"`
	Limit  int64  `json:"limit"`
}

type TopCategoriesByMonthRow struct {
	CategoryName *string     `json:"category_name"`
	Total        interface{} `json:"total"`
}

func (q *Queries) TopCategoriesByMonth(ctx context.Context, arg TopCategoriesByMonthParams) ([]TopCategoriesByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, topCategoriesByMonth, arg.Date, arg.Date_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopCategoriesByMonthRow{}
	for rows.Next() {
		var i TopCategoriesByMonthRow
		if err := rows.Scan(&i.CategoryName, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFinanceTransaction = `-- name: UpdateFinanceTransaction :one
UPDATE finance_transactions
SET date        = ?,
    amount      = ?,
    kind        = ?,
    account     = ?,
    category_id = ?,
    notes       = ?,
    recurrence  = ?
WHERE id = ?
RETURNING id, date, amount, kind, account, category_id, notes, recurrence, currency, created_at, updated_at, deleted_at
`

type UpdateFinanceTransactionParams struct {
	Date       string         `json:"date"`
	Amount     float64        `json:"amount"`
	Kind       string         `json:"kind"`
	Account    string         `json:"account"`
	CategoryID sql.NullInt64  `json:"category_id"`
	Notes      sql.NullString `json:"notes"`
	Recurrence string         `json:"recurrence"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateFinanceTransaction(ctx context.Context, arg UpdateFinanceTransactionParams) (FinanceTransaction, error) {
	row := q.db.QueryRowContext(ctx, updateFinanceTransaction,
		arg.Date,
		arg.Amount,
		arg.Kind,
		arg.Account,
		arg.CategoryID,
		arg.Notes,
		arg.Recurrence,
		arg.ID,
	)
	var i FinanceTransaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Amount,
		&i.Kind,
		&i.Account,
		&i.CategoryID,
		&i.Notes,
		&i.Recurrence,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
