// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Category struct {
	ID        int64  `json:"id"`
	Slug      string `json:"slug"`
	Name      string `json:"name"`
	Icon      string `json:"icon"`
	SortOrder int64  `json:"sort_order"`
}

type Resource struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	Type        string         `json:"type"`
	Language    string         `json:"language"`
	CategoryID  sql.NullInt64  `json:"category_id"`
	Notes       sql.NullString `json:"notes"`
	Favorite    int64          `json:"favorite"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	DeletedAt   sql.NullString `json:"deleted_at"`
}

type ResourceTag struct {
	ResourceID int64 `json:"resource_id"`
	TagID      int64 `json:"tag_id"`
}

type ResourcesFt struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Notes       string `json:"notes"`
	Tags        string `json:"tags"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type VResourceTag struct {
	ResourceID int64       `json:"resource_id"`
	Tags       interface{} `json:"tags"`
}
