// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type ArsenalConfig struct {
	K         string `json:"k"`
	V         string `json:"v"`
	UpdatedAt string `json:"updated_at"`
}

type CalendarEvent struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	StartAt     string         `json:"start_at"`
	EndAt       sql.NullString `json:"end_at"`
	AllDay      int64          `json:"all_day"`
	Location    string         `json:"location"`
	CategoryID  sql.NullInt64  `json:"category_id"`
	Notes       sql.NullString `json:"notes"`
	Recurrence  string         `json:"recurrence"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	DeletedAt   sql.NullString `json:"deleted_at"`
}

type CalendarFt struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Location    string `json:"location"`
}

type CalendarTag struct {
	EventID int64 `json:"event_id"`
	TagID   int64 `json:"tag_id"`
}

type Category struct {
	ID        int64  `json:"id"`
	Slug      string `json:"slug"`
	Name      string `json:"name"`
	Icon      string `json:"icon"`
	SortOrder int64  `json:"sort_order"`
}

type FinanceFt struct {
	Notes   string `json:"notes"`
	Account string `json:"account"`
}

type FinanceTag struct {
	FinanceID int64 `json:"finance_id"`
	TagID     int64 `json:"tag_id"`
}

type FinanceTransaction struct {
	ID         int64          `json:"id"`
	Date       string         `json:"date"`
	Amount     float64        `json:"amount"`
	Kind       string         `json:"kind"`
	Account    string         `json:"account"`
	CategoryID sql.NullInt64  `json:"category_id"`
	Notes      sql.NullString `json:"notes"`
	Recurrence string         `json:"recurrence"`
	Currency   string         `json:"currency"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	DeletedAt  sql.NullString `json:"deleted_at"`
}

type Resource struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	Type        string         `json:"type"`
	Language    string         `json:"language"`
	CategoryID  sql.NullInt64  `json:"category_id"`
	Notes       sql.NullString `json:"notes"`
	Favorite    int64          `json:"favorite"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	DeletedAt   sql.NullString `json:"deleted_at"`
}

type ResourceTag struct {
	ResourceID int64 `json:"resource_id"`
	TagID      int64 `json:"tag_id"`
}

type ResourcesFt struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Notes       string `json:"notes"`
	Tags        string `json:"tags"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Todo struct {
	ID          int64   `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Priority    string  `json:"priority"`
	Status      string  `json:"status"`
	DueDate     *string `json:"due_date"`
	CategoryID  *int64  `json:"category_id"`
	Notes       *string `json:"notes"`
	Recurrence  string  `json:"recurrence"`
	DoneAt      *string `json:"done_at"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	DeletedAt   *string `json:"deleted_at"`
}

type TodoTag struct {
	TodoID int64 `json:"todo_id"`
	TagID  int64 `json:"tag_id"`
}

type TodosFt struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Notes       string `json:"notes"`
	Tags        string `json:"tags"`
}

type VResourceTag struct {
	ResourceID int64       `json:"resource_id"`
	Tags       interface{} `json:"tags"`
}

type VTodoTag struct {
	TodoID int64       `json:"todo_id"`
	Tags   interface{} `json:"tags"`
}
