// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	AttachTag(ctx context.Context, arg AttachTagParams) error
	AttachTagToTodo(ctx context.Context, arg AttachTagToTodoParams) error
	CountOpenTodos(ctx context.Context) (int64, error)
	CountResources(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateResourceWithTimestamps(ctx context.Context, arg CreateResourceWithTimestampsParams) (Resource, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	DeleteCategory(ctx context.Context, id int64) error
	DeleteOrphanTags(ctx context.Context) error
	DeleteTag(ctx context.Context, id int64) error
	DetachAllTagsFromResource(ctx context.Context, resourceID int64) error
	// SearchTodos is hand-written in search.go (FTS5 MATCH not parseable by sqlc)
	DetachAllTagsFromTodo(ctx context.Context, todoID int64) error
	DetachTag(ctx context.Context, arg DetachTagParams) error
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetResource(ctx context.Context, id int64) (Resource, error)
	GetResourceByURL(ctx context.Context, url string) (Resource, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTodo(ctx context.Context, id int64) (Todo, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoriesWithCounts(ctx context.Context) ([]ListCategoriesWithCountsRow, error)
	ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error)
	ListTags(ctx context.Context) ([]ListTagsRow, error)
	ListTagsForResource(ctx context.Context, resourceID int64) ([]Tag, error)
	ListTagsForTodo(ctx context.Context, todoID int64) ([]Tag, error)
	ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error)
	ListTodosBasic(ctx context.Context, arg ListTodosBasicParams) ([]ListTodosBasicRow, error)
	ListTodosByStatus(ctx context.Context, status string) ([]Todo, error)
	ListTodosDueBefore(ctx context.Context, dueDate *string) ([]Todo, error)
	ListTodosDueBetween(ctx context.Context, arg ListTodosDueBetweenParams) ([]Todo, error)
	ListTrashedResources(ctx context.Context) ([]Resource, error)
	ListTrashedTodos(ctx context.Context) ([]Todo, error)
	MarkTodoDone(ctx context.Context, id int64) error
	MarkTodoOpen(ctx context.Context, id int64) error
	PurgeResource(ctx context.Context, id int64) error
	PurgeTodo(ctx context.Context, id int64) error
	RenameTag(ctx context.Context, arg RenameTagParams) (Tag, error)
	RestoreResource(ctx context.Context, id int64) error
	RestoreTodo(ctx context.Context, id int64) error
	SetFavorite(ctx context.Context, arg SetFavoriteParams) error
	SoftDeleteResource(ctx context.Context, id int64) error
	SoftDeleteTodo(ctx context.Context, id int64) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
	UpsertTag(ctx context.Context, name string) (Tag, error)
}

var _ Querier = (*Queries)(nil)
