// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	AttachTag(ctx context.Context, arg AttachTagParams) error
	CountResources(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateResourceWithTimestamps(ctx context.Context, arg CreateResourceWithTimestampsParams) (Resource, error)
	DeleteCategory(ctx context.Context, id int64) error
	DeleteOrphanTags(ctx context.Context) error
	DeleteTag(ctx context.Context, id int64) error
	DetachAllTagsFromResource(ctx context.Context, resourceID int64) error
	DetachTag(ctx context.Context, arg DetachTagParams) error
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetResource(ctx context.Context, id int64) (Resource, error)
	GetResourceByURL(ctx context.Context, url string) (Resource, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error)
	ListTags(ctx context.Context) ([]ListTagsRow, error)
	ListTagsForResource(ctx context.Context, resourceID int64) ([]Tag, error)
	ListTrashedResources(ctx context.Context) ([]Resource, error)
	PurgeResource(ctx context.Context, id int64) error
	RenameTag(ctx context.Context, arg RenameTagParams) (Tag, error)
	RestoreResource(ctx context.Context, id int64) error
	SetFavorite(ctx context.Context, arg SetFavoriteParams) error
	SoftDeleteResource(ctx context.Context, id int64) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpsertTag(ctx context.Context, name string) (Tag, error)
}

var _ Querier = (*Queries)(nil)
