// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package store

import (
	"context"
	"database/sql"
)

const countResources = `-- name: CountResources :one
SELECT COUNT(*) FROM resources WHERE deleted_at IS NULL
`

func (q *Queries) CountResources(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
    title, url, description, type, language, category_id, notes, favorite
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, title, url, description, type, language, category_id, notes, favorite, created_at, updated_at, deleted_at
`

type CreateResourceParams struct {
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	Type        string         `json:"type"`
	Language    string         `json:"language"`
	CategoryID  sql.NullInt64  `json:"category_id"`
	Notes       sql.NullString `json:"notes"`
	Favorite    int64          `json:"favorite"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.Type,
		arg.Language,
		arg.CategoryID,
		arg.Notes,
		arg.Favorite,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.CategoryID,
		&i.Notes,
		&i.Favorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createResourceWithTimestamps = `-- name: CreateResourceWithTimestamps :one
INSERT INTO resources (
    title, url, description, type, language, category_id, notes, favorite,
    created_at, updated_at, deleted_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, title, url, description, type, language, category_id, notes, favorite, created_at, updated_at, deleted_at
`

type CreateResourceWithTimestampsParams struct {
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	Type        string         `json:"type"`
	Language    string         `json:"language"`
	CategoryID  sql.NullInt64  `json:"category_id"`
	Notes       sql.NullString `json:"notes"`
	Favorite    int64          `json:"favorite"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	DeletedAt   sql.NullString `json:"deleted_at"`
}

func (q *Queries) CreateResourceWithTimestamps(ctx context.Context, arg CreateResourceWithTimestampsParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResourceWithTimestamps,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.Type,
		arg.Language,
		arg.CategoryID,
		arg.Notes,
		arg.Favorite,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.CategoryID,
		&i.Notes,
		&i.Favorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getResource = `-- name: GetResource :one
SELECT id, title, url, description, type, language, category_id, notes, favorite, created_at, updated_at, deleted_at FROM resources WHERE id = ? LIMIT 1
`

func (q *Queries) GetResource(ctx context.Context, id int64) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.CategoryID,
		&i.Notes,
		&i.Favorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getResourceByURL = `-- name: GetResourceByURL :one
SELECT id, title, url, description, type, language, category_id, notes, favorite, created_at, updated_at, deleted_at FROM resources WHERE url = ? LIMIT 1
`

func (q *Queries) GetResourceByURL(ctx context.Context, url string) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResourceByURL, url)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.CategoryID,
		&i.Notes,
		&i.Favorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, title, url, description, type, language, category_id, notes, favorite, created_at, updated_at, deleted_at FROM resources
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT  ?
OFFSET ?
`

type ListResourcesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.Type,
			&i.Language,
			&i.CategoryID,
			&i.Notes,
			&i.Favorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedResources = `-- name: ListTrashedResources :many
SELECT id, title, url, description, type, language, category_id, notes, favorite, created_at, updated_at, deleted_at FROM resources
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id DESC
`

func (q *Queries) ListTrashedResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listTrashedResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.Type,
			&i.Language,
			&i.CategoryID,
			&i.Notes,
			&i.Favorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeResource = `-- name: PurgeResource :exec
DELETE FROM resources WHERE id = ?
`

func (q *Queries) PurgeResource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, purgeResource, id)
	return err
}

const restoreResource = `-- name: RestoreResource :exec
UPDATE resources
SET deleted_at = NULL
WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreResource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreResource, id)
	return err
}

const setFavorite = `-- name: SetFavorite :exec
UPDATE resources SET favorite = ? WHERE id = ?
`

type SetFavoriteParams struct {
	Favorite int64 `json:"favorite"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, setFavorite, arg.Favorite, arg.ID)
	return err
}

const softDeleteResource = `-- name: SoftDeleteResource :exec
UPDATE resources
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteResource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteResource, id)
	return err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET title       = ?,
    url         = ?,
    description = ?,
    type        = ?,
    language    = ?,
    category_id = ?,
    notes       = ?
WHERE id = ?
RETURNING id, title, url, description, type, language, category_id, notes, favorite, created_at, updated_at, deleted_at
`

type UpdateResourceParams struct {
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	Type        string         `json:"type"`
	Language    string         `json:"language"`
	CategoryID  sql.NullInt64  `json:"category_id"`
	Notes       sql.NullString `json:"notes"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResource,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.Type,
		arg.Language,
		arg.CategoryID,
		arg.Notes,
		arg.ID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.CategoryID,
		&i.Notes,
		&i.Favorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
