// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package store

import (
	"context"
)

const attachTag = `-- name: AttachTag :exec
INSERT OR IGNORE INTO resource_tags (resource_id, tag_id) VALUES (?, ?)
`

type AttachTagParams struct {
	ResourceID int64 `json:"resource_id"`
	TagID      int64 `json:"tag_id"`
}

func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) error {
	_, err := q.db.ExecContext(ctx, attachTag, arg.ResourceID, arg.TagID)
	return err
}

const deleteOrphanTags = `-- name: DeleteOrphanTags :exec
DELETE FROM tags
WHERE id NOT IN (
    SELECT DISTINCT tag_id FROM resource_tags
    UNION
    SELECT DISTINCT tag_id FROM todo_tags
    UNION
    SELECT DISTINCT tag_id FROM finance_tags
)
`

func (q *Queries) DeleteOrphanTags(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanTags)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const detachAllTagsFromResource = `-- name: DetachAllTagsFromResource :exec
DELETE FROM resource_tags WHERE resource_id = ?
`

func (q *Queries) DetachAllTagsFromResource(ctx context.Context, resourceID int64) error {
	_, err := q.db.ExecContext(ctx, detachAllTagsFromResource, resourceID)
	return err
}

const detachTag = `-- name: DetachTag :exec
DELETE FROM resource_tags WHERE resource_id = ? AND tag_id = ?
`

type DetachTagParams struct {
	ResourceID int64 `json:"resource_id"`
	TagID      int64 `json:"tag_id"`
}

func (q *Queries) DetachTag(ctx context.Context, arg DetachTagParams) error {
	_, err := q.db.ExecContext(ctx, detachTag, arg.ResourceID, arg.TagID)
	return err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name FROM tags WHERE name = ? COLLATE NOCASE LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, COUNT(rt.resource_id) AS resource_count
FROM tags t
LEFT JOIN resource_tags rt ON rt.tag_id = t.id
GROUP BY t.id
ORDER BY t.name ASC
`

type ListTagsRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	ResourceCount int64  `json:"resource_count"`
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ResourceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForResource = `-- name: ListTagsForResource :many
SELECT t.id, t.name
FROM tags t
JOIN resource_tags rt ON rt.tag_id = t.id
WHERE rt.resource_id = ?
ORDER BY t.name ASC
`

func (q *Queries) ListTagsForResource(ctx context.Context, resourceID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTodo = `-- name: ListTagsForTodo :many
SELECT t.id, t.name
FROM tags t
JOIN todo_tags tt ON tt.tag_id = t.id
WHERE tt.todo_id = ?
ORDER BY t.name ASC
`

func (q *Queries) ListTagsForTodo(ctx context.Context, todoID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForTodo, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameTag = `-- name: RenameTag :one
UPDATE tags SET name = ? WHERE id = ? RETURNING id, name
`

type RenameTagParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) RenameTag(ctx context.Context, arg RenameTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, renameTag, arg.Name, arg.ID)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = excluded.name
RETURNING id, name
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
