// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package store

import (
	"context"
)

const attachTagToTodo = `-- name: AttachTagToTodo :exec
INSERT OR IGNORE INTO todo_tags (todo_id, tag_id) VALUES (?, ?)
`

type AttachTagToTodoParams struct {
	TodoID int64 `json:"todo_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AttachTagToTodo(ctx context.Context, arg AttachTagToTodoParams) error {
	_, err := q.db.ExecContext(ctx, attachTagToTodo, arg.TodoID, arg.TagID)
	return err
}

const countOpenTodos = `-- name: CountOpenTodos :one
SELECT COUNT(*) FROM todos WHERE status = 'open' AND deleted_at IS NULL
`

func (q *Queries) CountOpenTodos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenTodos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
    title, description, priority, status, due_date, category_id, notes, recurrence
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, title, description, priority, status, due_date, category_id, notes, recurrence, done_at, created_at, updated_at, deleted_at
`

type CreateTodoParams struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Priority    string  `json:"priority"`
	Status      string  `json:"status"`
	DueDate     *string `json:"due_date"`
	CategoryID  *int64  `json:"category_id"`
	Notes       *string `json:"notes"`
	Recurrence  string  `json:"recurrence"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.DueDate,
		arg.CategoryID,
		arg.Notes,
		arg.Recurrence,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.CategoryID,
		&i.Notes,
		&i.Recurrence,
		&i.DoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const detachAllTagsFromTodo = `-- name: DetachAllTagsFromTodo :exec

DELETE FROM todo_tags WHERE todo_id = ?
`

// SearchTodos is hand-written in search.go (FTS5 MATCH not parseable by sqlc)
func (q *Queries) DetachAllTagsFromTodo(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, detachAllTagsFromTodo, todoID)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, title, description, priority, status, due_date, category_id, notes, recurrence, done_at, created_at, updated_at, deleted_at FROM todos WHERE id = ? LIMIT 1
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.CategoryID,
		&i.Notes,
		&i.Recurrence,
		&i.DoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, description, priority, status, due_date, category_id, notes, recurrence, done_at, created_at, updated_at, deleted_at FROM todos
WHERE deleted_at IS NULL
ORDER BY due_date ASC NULLS LAST, created_at DESC, id DESC
LIMIT ?
OFFSET ?
`

type ListTodosParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByStatus = `-- name: ListTodosByStatus :many
SELECT id, title, description, priority, status, due_date, category_id, notes, recurrence, done_at, created_at, updated_at, deleted_at FROM todos
WHERE status = ? AND deleted_at IS NULL
ORDER BY due_date ASC NULLS LAST, created_at DESC, id DESC
`

func (q *Queries) ListTodosByStatus(ctx context.Context, status string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosDueBefore = `-- name: ListTodosDueBefore :many
SELECT id, title, description, priority, status, due_date, category_id, notes, recurrence, done_at, created_at, updated_at, deleted_at FROM todos
WHERE due_date < ? AND status = 'open' AND due_date IS NOT NULL AND deleted_at IS NULL
ORDER BY due_date ASC
`

func (q *Queries) ListTodosDueBefore(ctx context.Context, dueDate *string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosDueBefore, dueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosDueBetween = `-- name: ListTodosDueBetween :many
SELECT id, title, description, priority, status, due_date, category_id, notes, recurrence, done_at, created_at, updated_at, deleted_at FROM todos
WHERE due_date BETWEEN ? AND ? AND status = 'open' AND due_date IS NOT NULL AND deleted_at IS NULL
ORDER BY due_date ASC
`

type ListTodosDueBetweenParams struct {
	DueDate   *string `json:"due_date"`
	DueDate_2 *string `json:"due_date_2"`
}

func (q *Queries) ListTodosDueBetween(ctx context.Context, arg ListTodosDueBetweenParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosDueBetween, arg.DueDate, arg.DueDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosFiltered = `-- name: ListTodosFiltered :many
SELECT t.id, t.title, t.description, t.priority, t.status, t.due_date, t.category_id, t.notes, t.recurrence, t.done_at, t.created_at, t.updated_at, t.deleted_at, c.name AS category_name, c.slug AS category_slug,
       (
         SELECT COALESCE(GROUP_CONCAT(tag.name, ','), '')
         FROM todo_tags tt
         JOIN tags tag ON tag.id = tt.tag_id
         WHERE tt.todo_id = t.id
       ) AS tag_csv
FROM todos t
LEFT JOIN categories c ON c.id = t.category_id
WHERE (COALESCE(?1, 0) = 0 AND t.deleted_at IS NULL)
   OR (COALESCE(?1, 0) = 1 AND t.deleted_at IS NOT NULL)
ORDER BY t.due_date ASC NULLS LAST, t.created_at DESC, t.id DESC
LIMIT ?3 OFFSET ?2
`

type ListTodosFilteredParams struct {
	Trashed interface{} `json:"trashed"`
	Offset  *int64      `json:"offset"`
	Limit   *int64      `json:"limit"`
}

type ListTodosFilteredRow struct {
	ID           int64       `json:"id"`
	Title        string      `json:"title"`
	Description  *string     `json:"description"`
	Priority     string      `json:"priority"`
	Status       string      `json:"status"`
	DueDate      *string     `json:"due_date"`
	CategoryID   *int64      `json:"category_id"`
	Notes        *string     `json:"notes"`
	Recurrence   string      `json:"recurrence"`
	DoneAt       *string     `json:"done_at"`
	CreatedAt    string      `json:"created_at"`
	UpdatedAt    string      `json:"updated_at"`
	DeletedAt    *string     `json:"deleted_at"`
	CategoryName *string     `json:"category_name"`
	CategorySlug *string     `json:"category_slug"`
	TagCsv       interface{} `json:"tag_csv"`
}

func (q *Queries) ListTodosFiltered(ctx context.Context, arg ListTodosFilteredParams) ([]ListTodosFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodosFiltered, arg.Trashed, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodosFilteredRow{}
	for rows.Next() {
		var i ListTodosFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
			&i.CategorySlug,
			&i.TagCsv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedTodos = `-- name: ListTrashedTodos :many
SELECT id, title, description, priority, status, due_date, category_id, notes, recurrence, done_at, created_at, updated_at, deleted_at FROM todos
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id DESC
`

func (q *Queries) ListTrashedTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTrashedTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.CategoryID,
			&i.Notes,
			&i.Recurrence,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTodoDone = `-- name: MarkTodoDone :exec
UPDATE todos
SET status = 'done', done_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND status = 'open'
`

func (q *Queries) MarkTodoDone(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markTodoDone, id)
	return err
}

const markTodoOpen = `-- name: MarkTodoOpen :exec
UPDATE todos
SET status = 'open', done_at = NULL
WHERE id = ? AND status = 'done'
`

func (q *Queries) MarkTodoOpen(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markTodoOpen, id)
	return err
}

const purgeTodo = `-- name: PurgeTodo :exec
DELETE FROM todos WHERE id = ?
`

func (q *Queries) PurgeTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, purgeTodo, id)
	return err
}

const restoreTodo = `-- name: RestoreTodo :exec
UPDATE todos
SET deleted_at = NULL
WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreTodo, id)
	return err
}

const softDeleteTodo = `-- name: SoftDeleteTodo :exec
UPDATE todos
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteTodo, id)
	return err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title       = ?,
    description = ?,
    priority    = ?,
    status      = ?,
    due_date    = ?,
    category_id = ?,
    notes       = ?,
    recurrence  = ?
WHERE id = ?
RETURNING id, title, description, priority, status, due_date, category_id, notes, recurrence, done_at, created_at, updated_at, deleted_at
`

type UpdateTodoParams struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Priority    string  `json:"priority"`
	Status      string  `json:"status"`
	DueDate     *string `json:"due_date"`
	CategoryID  *int64  `json:"category_id"`
	Notes       *string `json:"notes"`
	Recurrence  string  `json:"recurrence"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.DueDate,
		arg.CategoryID,
		arg.Notes,
		arg.Recurrence,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.CategoryID,
		&i.Notes,
		&i.Recurrence,
		&i.DoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
